fedora-modularity/meta-test-family

moduleframework/common.py
moduleframework/mtf_generator.py

This PR updates docstrings for mtf-generator and common libs.

Docstrings for mtf-generator and common libs

---

docs/user_guide/scheduling.rst

This fixes only document.
Instead of Internal Jenkins document use Arbitrary Jenkins.

Remove Internal Jenkins instance

---

.landscape.yaml
README.md

This Pull Request adds Landscape - hosted continuous Python code metrics

Add Landscap.io into project

---

docs/api/common.rst
docs/api/exceptions.rst
docs/api/index.rst
moduleframework/common.py

This PR:
- adds and corrects docstrings, 
- changes some variables name to be descriptive,
- corrects indentation typos,
- corrects some unused variables,
- corrects other functions' syntax.
- updates docs API following PR #2

docstrings and some refactoring for common.py

---

docs/example-config-minimal.yaml
docs/example-config.yaml
examples/memcached/config.yaml
examples/testing-module/Makefile
meta-test-family.spec
moduleframework/common.py
moduleframework/environment_prepare/docker_prepare.py
moduleframework/environment_prepare/nspawn_prepare.py
moduleframework/environment_prepare/rpm_prepare.py
moduleframework/helpers/container_helper.py
moduleframework/helpers/nspawn_helper.py
moduleframework/helpers/rpm_helper.py
moduleframework/mtf_environment.py
moduleframework/pdc_data.py
setup.py
tools/run-them.sh

it is Work In progress,
It allows to split environment prepare and cleanup from tests, so that. it is done just ones time, on demand.
please do not merge it now.

Split prepare and cleanup for environment

---

setup.cfg

setup.cfg is needed for PyPi.
I would be glad for review.

Fixes #35 setup.cfg for PyPi

---

examples/testing-module/Makefile
tools/run-them.sh

* fix issue with exception test, by mistake removed --show-job-log, so unable to see exception
* added remote repos for every dependency, it will fix issue on taskotron

repair exception test, add remote repos for all dependencies

---

examples/rhscl_maria/config.yaml
examples/rhscl_maria/example1.py

Test for collections, example how to use it directly, without any modification

example of tests for collections

---

moduleframework/tools/modulelint.py

Remove BaseRuntime test

---

moduleframework/dockerlinter.py
moduleframework/tools/modulelint.py

This Pull Request fixes proper loading Dockerfile if it is defined by an environment variable
@jscotka Can you please have a look on it and review it?

Fixes #95: Proper handling Dockerfile

---

tools/mtf

- add help
- add possibility to include/exclude default linters run
- add possibility to pass arbitrary avocado args/tests files

Improve  executable:

---

docs/example-config.yaml
moduleframework/avocado_testers/avocado_test.py
moduleframework/common.py
moduleframework/environment_prepare/docker_prepare.py
moduleframework/environment_prepare/nspawn_prepare.py
moduleframework/environment_prepare/rpm_prepare.py
moduleframework/exceptions.py
moduleframework/mtf_environment.py

I partially added some user messages.
What do you more suggest to inform user about?

Print message for mtf-env-set

---

moduleframework/environment_prepare/docker_prepare.py
moduleframework/environment_prepare/nspawn_prepare.py
moduleframework/environment_prepare/rpm_prepare.py
moduleframework/mtf_environment.py

it shows testing name of the module from config.
Name of the module is from variable.

adding info about name of the module from loaded config

---

meta-test-family.spec
moduleframework/bashhelper.py
moduleframework/mtf_log_parser.py

Remove shebang from two python files

---

examples/rhscl_maria/example1.py
moduleframework/common.py
moduleframework/dockerlinter.py
moduleframework/helpers/container_helper.py
moduleframework/helpers/rpm_helper.py

* move default verrsion of base compose to F-27
* remove unique docker.io handling (causes tracekack in case container not defined)
* already be able to use just compose, instead of set of URLs

Small fixes

---

meta-test-family.spec

This Pull Request fixes wrong URL link to releases in SPEC file.

Fix SPEC URL

---

Makefile
examples/linter/f26-etcd/config.yaml
examples/linter/f26-flannel/config.yaml
examples/linter/rhscl-nginx/config.yaml
examples/linter/rhscl-postgresql/config.yaml
examples/linter/tools/Dockerfile
examples/linter/tools/config.yaml
examples/linter/tools/root/README.md

Would be awesome if mtf produced good results for these images. Please run the check before merging a PR and doing a release.
Fixes #132

add examples to test Red Hat and Fedora images

---

moduleframework/helpers/nspawn_helper.py

experimental support for systemd-run without --wait option

systemd-run backward compotibility (without wait option)

---

examples/testing-module/Dockerfile
examples/testing-module/help.md
meta-test-family.spec
moduleframework/dockerlinter.py
moduleframework/helpfile_linter.py
moduleframework/module_framework.py
moduleframework/mtf_environment.py
moduleframework/tools/dockerlint.py
moduleframework/tools/helpmd_lint.py
moduleframework/tools/modulelint.py
requirements.txt

Fix PR contains help.md sanity checks based on CBP

New checks in dockerlinter

---

docs/user_guide/environment_variables.rst
moduleframework/common.py
moduleframework/dockerlinter.py
moduleframework/tools/dockerlint.py
moduleframework/tools/helpmd_lint.py

This pull request fixes:
- add some log issues
- add support for yum checks

Fix some logging issues and yum checks

---

meta-test-family.spec
setup.py

Bump new release

---

moduleframework/dockerlinter.py
moduleframework/helpfile_linter.py

This Pull Request fixes issues detected during container-image-template usage
- fixes traceback in case COPY and ADD directives are not presen
- fixes error in case help_md does not exist.

Fixes #142 Fix false positives

---

meta-test-family.spec
setup.py

Bump version to 0.7.6

---

docs/user_guide/environment_setup.rst
examples/testing-module/Makefile

testsuite for mtf-init && docs for RTD

testsuite for mtf-init

---

MANIFEST.in
man/mtf-env-clean.1
man/mtf-env-set.1
man/mtf-generator.1
man/mtf.1
meta-test-family.spec
setup.py

This Pull Request brings all man pages for `mtf`, `mtf-env-clean` and `mtf-env-setup`.
The Review is important.

Manual page for Meta-Test-Family

---

meta-test-family.spec
setup.py

This only bumps version to 0.7.7 in order to build it to the latest one and test for container-image-template

Bump version to 0.7.7

---

Makefile.docs
docs/conf.py
moduleframework/dockerlinter.py
setup.py

This Pull Request fixes issues catched during document generation by sphinx.

Update RTD. Use sphinx-build-2

---

moduleframework/common.py

important fix for base-runtime / platform

fix profile handling

---

moduleframework/tools/__init__.py
moduleframework/tools/check_compose.py
moduleframework/tools/dockerlint.py
moduleframework/tools/helpmd_lint.py
moduleframework/tools/modulelint.py
moduleframework/tools/rpmvalidation.py

if you would like to use it, you can filter it now via avocado tag filters

add some tags to modulelint tests, to be able to filter them

---

tools/run_them_containers_taskotron.sh

it will be replacement for https://pagure.io/task-mtf-containers/blob/develop/f/run_mtf.sh 
what contains this code, and it is not so flexibile

script to run containers in taskotron

---

mtf/metadata/tmet/filter.py
mtf/metadata/tmet/selftests.py

it will be replacement for https://pagure.io/task-mtf-containers/blob/develop/f/run_mtf.sh 
what contains this code, and it is not so flexibile

fixing all issues in metadata modulelint

---

.travis.yml
Vagrantfile
docs/user_guide/environment_variables.rst
examples/testing-module/Makefile
meta-test-family.spec
moduleframework/common.py
moduleframework/helpers/container_helper.py
moduleframework/helpers/nspawn_helper.py
moduleframework/helpers/rpm_helper.py
moduleframework/pdc_data.py
moduleframework/pdc_msg_module_info_reader.py
setup.py
tools/run-them.sh

it is clean-up of PR #172
* add ODCS support
* cleaner classes structure in pdc_data module
* changes connected with this change
* improve recursive dependent module search

introduce ODCS support  to MTF PR#172

---

.gitignore
.travis.yml
MANIFEST.in
man/mtf-env-clean.1
man/mtf-env-set.1
man/mtf-generator.1
moduleframework/mtf_environment.py
moduleframework/mtf_generator.py
setup.cfg
setup.py

Reverts fedora-modularity/meta-test-family#180

Revert "remove all manpages"

---

examples/s2i-python-sample/simpleTest.py
moduleframework/avocado_testers/avocado_test.py
moduleframework/avocado_testers/nspawn_avocado_test.py
moduleframework/common.py
moduleframework/environment_prepare/docker_prepare.py
moduleframework/environment_prepare/nspawn_prepare.py
moduleframework/helpers/container_helper.py
moduleframework/helpers/nspawn_helper.py
moduleframework/helpers/openshift_helper.py
moduleframework/helpers/rpm_helper.py
setup.py

This Pull Request implements one feature. @property, setter and getter.
I have tried to find out all issues, where we can use it and hopefully, I catched all of them.

Propery setter getter

---

docs/example-config.yaml
docs/user_guide/environment_variables.rst
moduleframework/common.py
moduleframework/dockerlinter.py
moduleframework/helpfile_linter.py
moduleframework/tools/dockerlint.py
moduleframework/tools/helpmd_lint.py

- it fixes HelpMD handling, to be on same level as Dockerfile,
- removed uwanted imports
- add docs about this option

helpmd and docker lint cleanup of loading classes

---

mtf/metadata/Makefile
mtf/metadata/README.md
mtf/metadata/examples/general-component/tests/metadata.yaml
mtf/metadata/tmet/agregator.py
mtf/metadata/tmet/common.py
mtf/metadata/tmet/selftests.py

Use metadata file to download files from some URL location to local files

RFE: url_downloader option in metadata.yaml allows download tests via URLlib

---

mtf/metadata/Makefile
mtf/metadata/examples/general-component/tests/metadata.yaml
mtf/metadata/tmet/common.py
mtf/metadata/tmet/selftests.py

please not merge it now, I have to check few issues

speed optimization for avocado based test tag filtering

---

.travis.yml
examples/memcached/config.yaml
examples/openshift-sample/config.yaml
examples/openshift-sample/sanity1.py
examples/testing-module/Makefile
moduleframework/avocado_testers/avocado_test.py
moduleframework/common.py
moduleframework/helpers/container_helper.py
moduleframework/helpers/openshift_helper.py
moduleframework/mtf_scheduler.py

This Pull Request introduce testing container inside OpenShift.
As a testing container memcached is used.

Include OpenShift into Travis CI and testing

---

docs/api/bashhelper.rst
docs/api/index.rst
docs/api/version.rst
docs/conf.py
docs/index.rst
docs/user_guide/index.rst
docs/user_guide/mtf_linters.rst

This Pull Request introduces docuementation about MTF linters.
Reference to MTF issue is: #202
It contains as dockerfile linters as help file linters.

Documentation for MTF linters

---

.travis.yml
Makefile
examples/s2i-python-sample/Makefile
examples/s2i-python-sample/simpleTest.py
examples/testing-module/Makefile
moduleframework/avocado_testers/avocado_test.py
moduleframework/common.py
moduleframework/mtf_environment.py
moduleframework/mtf_generator.py
moduleframework/mtf_scheduler.py
moduleframework/mtfexceptions.py
moduleframework/pdc_data.py

Have to fix all travis issues before merging
* fix PDC (changed namespace)
* fix base compose URL  (composes from koji removed)
* simplify debug output
* simplify tools (option handling)
* use better heureistic which modules can be used
* collect skips and fails together, to not mix them

fix various issues mentioned in  issue  #201

---

moduleframework/common.py
moduleframework/helpers/rpm_helper.py
moduleframework/pdc_data.py

moved some function from PDC part to common library, to avoid dependency in rpm helper

moved functions not dependent on PDC to common and use then common in rpm helper

---

examples/mtf-linters/Makefile
examples/mtf-linters/test_from.py
examples/mtf-linters/test_volume.py
moduleframework/dockerlinter.py

This issue fixes #222  and brings more tests for linters.

Fix issue with VOLUME and add VOLUME dockerlint tests

---

moduleframework/tests/static/dockerfile_lint.py

This Pull Request only removes the architecture label test.

Fixes #232 Removing architecture label test
